rollback

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -35,18 +35,47 @@ jobs:
         with:
           go-version: ${{ env.GO_VERSION }}
 
+      - name: Setup PATH
+        run: echo "::add-path::${GOPATH}/bin"
+
+      - name: Install dependencies
+        run: make deps && go get -v github.com/mattn/goveralls
+
+      - name: Install/Downgrade MongoDB to version 3.6
+        run: |
+          wget -qO - https://www.mongodb.org/static/pgp/server-3.6.asc | sudo apt-key add -
+          echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
+          sudo apt-get update
+          sudo apt-get install -y --allow-downgrades mongodb-org=3.6.20 mongodb-org-server=3.6.20 mongodb-org-shell=3.6.20 mongodb-org-mongos=3.6.20 mongodb-org-tools=3.6.20 || echo "Error is misleading, it was successfully installed"
+
+      - name: Unit Tests
+        run: glide novendor| xargs go test -v
+
+      - name: Create cover profile
+        run: make coverprofile
+
+      - name: Run Docker Test
+        run: make dockertest
+
+      - name: Submit Coveralls
+        env:
+          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: goveralls -coverprofile=cover.profile -service=github
+
       # Push to dockerhub
       - name: Push user to Docker Hub
-        uses: docker/build-push-action@v2
+        uses: docker/build-push-action@v1
+        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
         with:
           push: false
-          file: docker/user/Dockerfile-release
+          dockerfile: docker/user/Dockerfile-release
           repository: ${{ env.GROUP }}/${{ env.REPO }}
           tag_with_ref: true
           tag_with_sha: true
 
       - name: Push user-db to Docker Hub
         uses: docker/build-push-action@v1
+        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
         with:
           push: false
           dockerfile: docker/user-db/Dockerfile
@@ -54,4 +83,3 @@ jobs:
           repository: ${{ env.GROUP }}/${{ env.REPO }}
           tag_with_ref: true
           tag_with_sha: true
-
